import java.util.Scanner;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public static void main(String[] args) {
        Scanner sc = new Scanner(System.in);
        String message = sc.nextLine();
        Mobile mobile = new Mobile("JerryLi","black","201516080209");
        mobile.call(message);

        Iphone iphone = new Iphone("JerryLi","black","201516080209");
        iphone.call(message);

        Andriod andriod = new Andriod("JerryLi","black","201516080209");
        andriod.call(message);
    }
}
